name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional, only needed for builds using Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Change this to your required Node.js version

      # Step 3: Install dependencies and build the site (if required)
      - name: Install Dependencies
        run: npm ci # Change this if you're using another package manager (e.g., yarn)

      - name: Build the Site
        run: npm run build # Change to your build command, e.g., `vite build`

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Change this to your output directory
